security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user:
            entity:
                class: App\Entity\User
        jwt_user:
            lexik_jwt:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/login
            provider: app_user
            form_login:
                success_handler: app.jwt_authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                password_parameter: password
                username_parameter: username
                require_previous_session: false
                check_path: app_login
            entry_point: form_login
            refresh_jwt:
                check_path: refresh_login
            #login_throttling: max_attempts: 5
        main:
            provider: app_user
            stateless: true
            logout: true
            lazy: true
            jwt: ~

    access_control:
        - { path: ^/api/(products|tags), roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/(api/(docs|docs.json)|register|login), roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin,   roles: ROLE_ADMIN }
        - { path: ^/api,     roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon