app.swagger_ui:
    path: /api/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

controllers:
    resource: ../src/Controller/
    type: attribute

api_platform:
    resource: ../src/Controller/Api/
    prefix: /api
    type: attribute

app_logout:
    path: /logout

refresh_login:
    path: /login/refresh
    methods: ['POST']